// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnyjtdioyjcsmqxxutcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNueWp0ZGlveWpjc21xeHh1dGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTk2NTMsImV4cCI6MjA3MjY3NTY1M30.Wl4SukWN3lYAhA2a5AORzZVm8jPfmuXVtEUX9IDNuxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});